apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-worker
  namespace: url-shortener
spec:
  replicas: 1                         # Only need 1 worker consuming the queue
  selector:
    matchLabels:
      app: analytics-worker
  template:
    metadata:
      labels:
        app: analytics-worker
    spec:
      containers:
        - name: analytics-worker
          image: minikube/analytics-worker:latest  # add :latest
          imagePullPolicy: Never   # use local image only
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASS
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
